services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/nithinjd06/n8n
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: GENERIC_TIMEZONE
        value: America/Chicago
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: yourusername
      - key: N8N_BASIC_AUTH_PASSWORD
        value: yoursecurepassword
